### ISSUE TITLE
Fetch and format youtube videos for the Video page

### ISSUE THREAD

**Issue by TheKnarf** [Alv-no/alv-website#35]
~We need a schema in Sanity for adding youtube videos for the video page.~

**Comment by mikkelcodes** [comment]
I have exceeded my api request quota due to issues with infinite callback loops, and cannot progress on this issue before I sort myself with a new apikey. But Video cards are being generated with their featured section on top and in the playlists they belong in. This was certainly more time consuming to set up than expected - none of the plugins were useful and so the request had to be made using fetch/axios. This portion of the code currently lives inside the videoseries component, and should probably be transferred over to gatsby-node.js so that playlist info and videos info is fetched at build time rather than runtime
